apiVersion: apps/v1
kind: Deployment
metadata:
  name: userauthapp
  labels:
    app: userauthapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userauthapp
  template:
    metadata:
      labels:
        app: userauthapp
    spec:
      containers:
        - name: userauthapp
          image: anirbanbh/userauthapp:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "120m"
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
