apiVersion: v1
kind: Service
metadata:
  name: userauthapp-lb-svc
spec:
  selector:
    app: userauthapp
  ports:
    - protocol: "TCP"
      port: 9000
      targetPort: 5000
  type: LoadBalancer
